blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.archive),
    url(r'^create/', views.create_blogpost),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^w3c/', include('w3c.urls', namespace="w3c")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name="results"),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
    url(r'^keyboard/', views.keyboard, name="keyboard"),
    url(r'^player/', views.player, name="player"),
]

w3c/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django import forms

# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    timestamp = models.DateTimeField()


class BlogPostForm(forms.ModelForm):
    class Meta():
        model = BlogPost
        exclude = ('timestamp',)

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

w3c/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone

# Create your models here.


class CityGallery(models.Model):
    city_name_text = models.CharField(max_length=20)
    city_introduce_text = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render
from blog.models import BlogPost,BlogPostForm
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/templates/blog/'

# Create your views here.


def archive(request):
    posts = BlogPost.objects.all()[:10]
    return render(request, BASE_DIR+'archive.html',
                  {'posts': posts, 'form': BlogPostForm()})

def create_blogpost(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.timestamp = datetime.now()
            post.save()
        return HttpResponseRedirect('/blog/')

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone


from .models import Question, Choice

# Create your views here.

#self test
def keyboard(request):
    return render(request, 'polls/keyboard.html')

def player(request):
    return render(request, 'polls/player.html')


#eg.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html',
                    {'question': p, 'error_message': "You didn't select a choice.",}
                    )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

w3c/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import CityGallery

# Create your views here.
class IndexView(generic.ListView):

    #设置使用的模板
    template_name = 'w3c/index.html'

    # 自定义上下文变量
    context_object_name = 'latest_cities_list'

    def get_queryset(self):
        """
            重写 get_queryset 方法，取出发表的内容
        """
        return CityGallery.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = CityGallery
    template_name = 'w3c/detail.html'
    context_object_name = "city"
    pk_url_kwargs = "pk"


    def get_object(self,queryset=None):
        index=int(self.kwargs.get(self.pk_url_kwargs, None)) - 1
        return CityGallery.objects.filter(pub_date__lte=timezone.now())[index]

blog/templates/blog/archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!-- archive.html -->
<form action="/blog/create/" method=post>{% csrf_token %}
<table>{{ form }}</table><br>
<input type=submit>
</form>
<hr>

<!-- archive.html -->
{% for post in posts %}
<h2>{{ post.title }}</h2>
<p>{{ post.timestamp }}</p>
<p>{{ post.body }}</p>
<hr>
{% endfor %}
</body>
</html>

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Generic welcome to your web page [Login - Help - FAQ]
<h1>Blog Central</h1>
{% block content %}
{% endblock %}
&copy; 2011 your company [About - Contact]

</body>

</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!-- index.html -->
{% extends "base.html" %}
{% block content %}
{% for post in posts %}
<h2>{{ post.title }}</h2>
<p>{{ post.timestamp }}</p>
<p>{{ post.body }}</p>
<hr>
{% endfor %}
{% endblock %}

</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />
</head>

<body>

    <ul id="ul_title">
        <li id="li_home"><a id="a_home" href="#home">Home</a></li>
        <li id="li_news"><a id="a_news" href="#news">News</a></li>
        <li id="li_contact"><a id="a_contact" href="#contact">Contact</a></li>
        <li id="li_about"><a id="a_about" href="#about">About</a></li>
    </ul>


    {% if latest_question_list %}
    <ul id="ul_context">
        {% for question in latest_question_list %}
        <li><a id="a_context" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}

</body>

</html>

polls/templates/polls/keyboard.html
<!DOCTYPE html>
<html >
<head>
<meta charset="UTF-8">
<title>李夏衍的五彩炫酷模拟键盘DEMO演示</title>

<style type="text/css">
	body{ background: #000;}
	textarea{ display:block;width:880px; height: 100px; margin: 50px auto; font-size: 16px; color:#fff; background: #555;}
	.keyboard{ width:908px; margin: 50px auto;}
</style>

<script type="text/javascript" src="/static/polls/js/jquery-3.2.1.js"></script>
<script type="text/javascript" src="/static/polls/js/keyboard.min.js"></script>

</head>
<body>

<textarea placeholder=" 请在这里输入英文！！！"></textarea>

<div class="keyboard"></div>


<script type="text/javascript">
    $('textarea').focus();
	$('.keyboard').keyboard({audio:'/media/polls/music/keydown.mp3'});
</script>


<div style="text-align:center;clear:both">
<script src="/gg_bd_ad_720x90.js" type="text/javascript"></script>
<script src="/follow.js" type="text/javascript"></script>
</div>


</body>
</html>

polls/templates/polls/player.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Video.js 6.2.5</title>
	<link href="css/video-js.css" rel="stylesheet">
	<style>
		body{background-color: #191919}
		.m{ width: 740px; height: 400px; margin-left: auto; margin-right: auto; margin-top: 100px; }
	</style>
</head>

<body>
	<div class="m">
		<video id="my-video" class="video-js" controls preload="auto" width="740" height="400"
               poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
            <source src="/media/polls/video/bird.mp4" type="video/mp4">
            <!--
            <source src="/media/polls/video/bird.mp4" type="video/mp4">
			<source src="http://vjs.zencdn.net/v/oceans.webm" type="video/webm">
			<source src="http://vjs.zencdn.net/v/oceans.ogv" type="video/ogg">
			-->
			<p class="vjs-no-js">
			  To view this video please enable JavaScript, and consider upgrading to a web browser that
			  <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
			</p>
        </video>
        <script src="/static/polls/video.min.js"></script>
        <script type="text/javascript">
			var myPlayer = videojs('my-video');
			videojs("my-video").ready(function(){
				var myPlayer = this;
				myPlayer.play();
			});
		</script>
	</div>

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

w3c/templates/w3c/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>W3C</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'w3c/css/style.css' %}" />
</head>
<body>

<div id="header">
<h1>{{ city.city_name_text }}</h1>
</div>

<div id="section">
    <p>{{ city.city_introduce_text }}</p>
</div>

<div id="footer">
Copyright W3School.com.cn
</div>

</body>
</html>

w3c/templates/w3c/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>W3C</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'w3c/css/style.css' %}" />
</head>
<body>

<div id="header">
<h1>City Gallery</h1>
</div>

<div id="nav">
    {% for city in latest_cities_list %}
    <li><a id="a_title" href="{% url 'w3c:detail' city.id %}">{{ city.city_name_text }}</a></li>
    {% endfor %}
</div>


<div id="footer">
Copyright W3School.com.cn
</div>

</body>
</html>